// Generated by   : ImageConverter Mono Online
// Generated from : sjors_action2.gif
// Time generated : Wed, 16 Aug 17 15:14:29 +0200  (Server timezone: CET)
// Image Size     : 18x8 pixels
// Memory usage   : 18 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype sjors_action2[] PROGMEM={
0x05, 0x22, 0x53, 0x12, 0x73, 0x33, 0x62, 0xC5, 0x01, 0x00, 0xC4, 0x62, 0x12, 0x72, 0x32, 0x52,   // 0x0010 (16) pixels
0x22, 0x04, 
};
