// Generated by   : ImageConverter Mono Online
// Generated from : sjors_action3.gif
// Time generated : Wed, 16 Aug 17 15:14:38 +0200  (Server timezone: CET)
// Image Size     : 18x8 pixels
// Memory usage   : 18 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype sjors_action3[] PROGMEM={
0x03, 0x21, 0x51, 0x11, 0x71, 0x31, 0x61, 0xC3, 0x01, 0x00, 0xC2, 0x61, 0x11, 0x71, 0x31, 0x51,   // 0x0010 (16) pixels
0x21, 0x02, 
};
