// Generated by   : ImageConverter Mono Online
// Generated from : sjors_eyes0.gif
// Time generated : Wed, 16 Aug 17 16:12:35 +0200  (Server timezone: CET)
// Image Size     : 18x8 pixels
// Memory usage   : 18 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype sjors_eyes0[] PROGMEM={
0x08, 0x34, 0x55, 0x14, 0x75, 0x35, 0x64, 0xC9, 0x01, 0x00, 0xC8, 0x64, 0x14, 0x74, 0x34, 0x54,   // 0x0010 (16) pixels
0x24, 0x08, 
};
